# Summerization code using ChatGPT API
import openai
import os

# Load OpenAI API key from file
with open('openai_key.txt', 'r') as f:
    api_key = f.read().strip()

# Authenticate with OpenAI API
openai.api_key = api_key

def summarize_text(text):
    """
    Summarize the input text using the OpenAI GPT-3 API.

    Args:
    text (str): Input text to be summarized.

    Returns:
    summary (str): Summary of the input text generated by the API.
    """
    # Use the GPT-3 "davinci" model for summarization
    model_engine = "davinci"

    # Set the prompt for the API request
    prompt = (f"Please summarize the following text:\n"
              f"{text}\n"
              f"Summary:")

    # Call the OpenAI API to generate a summary
    response = openai.Completion.create(
        engine=model_engine,
        prompt=prompt,
        max_tokens=60,
        n=1,
        stop=None,
        temperature=0.7,
    )

    # Extract the summary from the API response
    summary = response.choices[0].text.strip()

    return summary

# Example text to summarize
text = """The COVID-19 pandemic has had a major impact on the world, causing widespread illness, death, and social and economic disruption. 
        The pandemic has highlighted the importance of public health and healthcare systems, as well as the need for scientific research 
        to develop effective treatments and vaccines. Governments and organizations around the world have taken a range of measures 
        to respond to the pandemic, including lockdowns, travel restrictions, and vaccine distribution efforts."""

# Summarize the text using the OpenAI GPT-3 API
summary = summarize_text(text)

# Print the summary
print(summary)
